### ISSUE TITLE
Hide messages outside of specific channels

### ISSUE THREAD

**Issue by felacek** [martinmladenov/RankingBot#96]
/ranks and /offers messages should be hidden in all channels but bot-spam, because it clutters the channel and forces people to block the bot.

Role reminder messages should always be hidden.

**Comment by martinmladenov** [comment]
> /ranks and /offers messages should be hidden in all channels but bot-spam,

I agree. This can easily be done by passing an argument to `ctx.send`. In addition, I would also add /offergraph to this list. Maybe an optional command argument could be added to those commands in order to allow them to be sent to all users if necessary (e.g. if someone else asks what the current graph and you want to show them the graph itself)

> Role reminder messages should always be hidden.

This one is a bit more tricky. It cannot be hidden since it's not a response to an interaction (e.g. a command, a button press, etc.). However, we could set it so that the bot deletes those messages after one minute.
